// <auto-generated />
namespace JOTB_Restauracja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodanie_ilosci_do_produktu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanie_ilosci_do_produktu));
        
        string IMigrationMetadata.Id
        {
            get { return "201604141927410_dodanie_ilosci_do_produktu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
